config/routes.rb
Rails.application.routes.draw do

  get 'homes/top'
  get 'homes/about'
  get "search_result" => "searchs#search_result"
  root to: "homes#top"

  # 管理者
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :admin do
    resources :games
  end

  namespace :admin do
    resources :questions
    resources :questions do
      resources :comments, only: [:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :admin do
    resources :tags
  end

  namespace :admin do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :admin do
    devise_scope :user do
      post 'users/:id', to: 'sessions#guest_sign_in', as: 'guest_sign_in'
    end

    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups
    end

  #ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :games
  end

  namespace :public do
    resources :questions
    resources :questions, except: [:destroy] do
      resources :comments, only: [:create,:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :public do
    resources :tags
  end

  namespace :public do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :public do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :public do
    devise_scope :user do
      post 'user/guest_sign_in' => 'sessions#guest_sign_in', as: 'guest_sign_in'
    end
  end

  namespace :public do
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups do
      get "join" => "groups#join"
      get "group/:id/member" => "groups#member", as: 'members'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/question.rb
class Question < ApplicationRecord
  has_one_attached :image
  has_many_attached:question_images

  belongs_to :user
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 200 }
  validates :question, presence: true, length: { maximum: 1000 }

  # ブックマーク機能
  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  # 検索機能
  def self.looks(search, word)
      @question = Question.where("title LIKE?","%#{word}%")
  end

  # タグ検索機能
  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(tag_name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_tagmap = Tag.find_or_create_by(tag_name: new)
      self.tags << new_tagmap
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  def index
    @users = User.all
    @questions = Question.all.order("id DESC").page(params[:page]).per(20)
    # @questions = Question.order("id DESC").page(params[:page]).per(20)
    @tag_list = Tag.all
    @tag_list = Tag.order("id DESC")
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    tag_list = params[:question][:tag_name].split(',')
    if @question.save
      @question.save_tag(tag_list)
      # binding.pry
      redirect_to public_question_path(@question.id)
    else
      render:new
    end
  end

  def show
    @question = Question.find(params[:id])
    @comment = Comment.new
    @comment = Comment.all
    @comments = @question.comments
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to public_question_path(@question.id)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to admin_questions_path
  end

  def search_tag
    @tag_list = Tag.all
    @tag_list = Tag.order("id DESC")
    @tag = Tag.find(params[:tag_id])
    @questions = @tag.questions.order("id DESC")
    @users = User.all
  end

  def bookmark
    @bookmarks = Bookmark.where(user_id: current_user.id)
    @bookmarks = Bookmark.order("id DESC").page(params[:page]).per(20)
  end

  def correct_user
    @question = Question.find(params[:id])
    @user = @question.user
    redirect_to(public_questions_path) unless @user == current_user
  end


  private

  def question_params
    params.require(:question).permit(:title,:question,:game_id,:image, question_images: [])
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/views/admin/questions/edit.html.erb
<h1>Admin::Questions#edit</h1>
<p>Find me in app/views/admin/questions/edit.html.erb</p>

app/views/admin/questions/index.html.erb
<%= stylesheet_link_tag 'questions', :media => "all" %>
<%= stylesheet_link_tag 'tags', :media => "all" %>
<%= stylesheet_link_tag 'titles', :media => "all" %>

<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <div class="row">

          <div class="col-lg-12">

            <div class="main-profile">

              <div class="row">

                <div class="col-lg-12">

                  <div class="album py-2">

                    <h1 class="my-questions-title"><strong><i class="fa-solid fa-clipboard-question"></i> <span>E</span>veryone's <span>Q</span>uestions</strong></h1>

                    <% @questions.each do |question| %>

                      <div class="row">

                        <div class="col-lg-2 col-sm-2 my-questions">

                          <%= link_to public_user_path(question.user.id) do %>
                            <%= image_tag question.user.get_profile_image, style: "border-radius: 50%;", class: "user_image_question" %>
                          <% end %>

                        </div>

                        <div class="col-lg-10 col-sm-10 my-questions">

                          <p>
                            <span class="question-user-name" ><strong><%= question.user.user_name %></strong></span>
                            <span class="up-time text-muted"><%= question.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></span>
                          </p>

                          <div class="question-body">

                            <p class="question-title"><strong><%= question.title %></strong></p>

                            <div class="d-flex justify-content-between align-items-center">

                              <p class="question-contents"><%= question.question %></p>

                            </div>

                            <div class="question-images">
                              <% if question.question_images.attached? %>
                                <% question.question_images.each do |image| %>
                                  <%= image_tag image, style: "border-radius: 20px;", class:'question-image' %>
                                <% end %>
                              <% end %>
                            </div>

                            <div class="text-right">

                              <span>
                                <%= link_to admin_question_path(question.id), class: "show-link" do  %>
                                  <i class="fa-solid fa-door-open" style="color: #ec6090; font-size: 30px;"></i>
                                <% end %>
                              </span>

                            </div>

                          </div>

                        </div>

                      </div>

                      <div class="border-bottom border-dark"></div>

                    <% end %>

                  </div>

                </div>

              </div>

            </div>

            <div class="row">
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
                <div class="col-lg-6 col-sm-6 col-xs-6 pagi-nation">
                  <%= paginate @questions %>
                </div>
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>

app/views/admin/questions/show.html.erb
<%= stylesheet_link_tag 'show_questions', :media => "all" %>

<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <div class="row">

          <div class="col-lg-12">

            <div class="main-profile">

              <div class="row">

                <div class="col-lg-12">

                  <div class="album py-2">

                    <h1 class="my-questions-title"><strong><i class="fa-solid fa-clipboard-question"></i> <span><%= @question.user.user_name %></span>'s <span>Q</span>uestion</strong></h1>

                    <div class="row">

                      <div class="col-lg-2 col-sm-2 col-xs-2 my-questions">

                        <%= link_to admin_user_path(@question.user.id) do %>
                          <%= image_tag @question.user.get_profile_image, style: "border-radius: 100px;", class: "user_image_question" %>
                        <% end %>

                      </div>

                      <div class="col-lg-10 col-sm-10 col-xs-10 my-questions">

                        <p>
                          <span class="question-user-name" ><strong><%= @question.user.user_name %></strong></span>
                          <span class="up-time text-muted"><%= @question.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></span>
                        </p>

                        <div class="question-body">

                          <p class="question-title"><strong><%= @question.title %></strong></p>

                          <div class="d-flex justify-content-between align-items-center">

                            <p class="question-contents"><%= @question.question %></p>

                          </div>

                          <div class="ol-lg-12 col-sm-12 col-xs-12 question-images">
                            <% if @question.question_images.attached? %>
                              <% @question.question_images.each do |image| %>
                                <%= image_tag image, style: "border-radius: 20px;", class:'question-image' %>
                              <% end %>
                            <% end %>
                          </div>

                          <div class="text-right">

                            <span>
                              <%= link_to admin_question_path(@question.id), class: "show-link", method: :delete do %>
                                <i class="fa-solid fa-trash-can"  style="color: red; font-size: 30px;"></i>
                              <% end %>
                            </span>

                          </div>

                        </div>

                      </div>

                    </div>

                    <div class="mb-5 border-bottom border-dark"></div>

                    <h1 class="comments"><strong><i class="fa-solid fa-comments"></i> <span>C</span>omments</strong></h1>

                    <% @question.comments.each do |comment| %>

                      <div class="row">

                        <div class="col-lg-1 col-sm-1 col-xs-1 my-questions">

                          <%= link_to public_user_path(comment.user.id) do %>
                            <%= image_tag comment.user.get_profile_image, style: "border-radius: 100px;", class: "user_image_question" %>
                          <% end %>

                        </div>

                        <div class="col-lg-11 col-sm-11 col-xs-11 my-questions">

                          <p>
                            <span class="question-user-name" ><strong><%= comment.user.user_name %></strong></span>
                            <span class="up-time text-muted"><%= comment.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></span>
                          </p>

                          <div class="question-body">

                            <div class="d-flex justify-content-between align-items-center">

                              <p class="question-contents"><%= comment.comment %></p>

                            </div>

                            <div class="text-right">

                              <% if user_signed_in? && comment.user == current_user %>
                                <%= link_to public_question_comment_path(comment.question.id, commentid), method: :delete do %>
                                  <i class="fa-solid fa-trash-can" style="color: red; font-size: 30px;"></i>
                                <% end %>
                                <% elsif admin_signed_in? %>
                                <%= link_to "管理者削除", admin_question_comment_path(comment.question.id, comment.id), method: :delete, class: "btn btn-sm btn-danger p-0 p-1", style: "font-size: 20px;" %>
                              <% end %>

                            </div>

                          </div>

                        </div>

                      </div>

                      <div class="border-bottom border-dark"></div>

                    <% end %>

                  </div>

                </div>

              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>