config/routes.rb
Rails.application.routes.draw do

  get 'homes/top'
  get 'homes/about'
  get "search_result" => "searchs#search_result"
  root to: "homes#top"

  # 管理者
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :admin do
    resources :games
  end

  namespace :admin do
    resources :questions
    resources :questions do
      resources :comments, only: [:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :admin do
    resources :tags
  end

  namespace :admin do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :admin do
    devise_scope :user do
      post 'users/:id', to: 'sessions#guest_sign_in', as: 'guest_sign_in'
    end

    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups
    end

  #ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :games
  end

  namespace :public do
    resources :questions
    resources :questions, except: [:destroy] do
      resources :comments, only: [:create,:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :public do
    resources :tags
  end

  namespace :public do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :public do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :public do
    devise_scope :user do
      post 'user/guest_sign_in' => 'sessions#guest_sign_in', as: 'guest_sign_in'
    end
  end

  namespace :public do
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups do
      get "join" => "groups#join"
      get "group/:id/member" => "groups#member", as: 'members'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, presence: true, length: { maximum: 1000 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController

  def index
    @question = Question.new
    @groups = Group.all.order("id DESC").page(params[:page]).per(20)
    # @groups = Group.order("id DESC")
    @group = Group.new
  end

  def show
    @question = Question.all
    @group = Group.find(params[:id])
    @group_comment = GroupComment.new
    @group_comment = GroupComment.all
    @group_comments = @group.group_comments
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to public_group_path(@group.id)
    else
      render "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to admin_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name,:introduction,:image)
  end


end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/edit.html.erb
<h1>Admin::Groups#edit</h1>
<p>Find me in app/views/admin/groups/edit.html.erb</p>

app/views/admin/groups/index.html.erb
<%= stylesheet_link_tag 'questions', :media => "all" %>
<%= stylesheet_link_tag 'titles', :media => "all" %>
<%= stylesheet_link_tag 'show_questions', :media => "all" %>

<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <div class="row">

          <div class="col-lg-12">

            <div class="main-profile">

              <div class="row">

                <div class="col-lg-12">

                  <div class="album py-2">

                    <div class="row">

                      <div class="col-lg-6 col-sm-6 col-xs-6 my-questions">
                        <h1 class="my-questions-title"><strong><i class="fa-solid fa-people-group"></i> <span>G</span>roups</strong></h1>
                      </div>

                      <div class="col-lg-6 col-sm-6 col-xs-6 up-button" style="text-align: center;">
                        <%=link_to "グループを作成する",new_public_group_path, class:'btn btn-outline-light', style: "color: #ec6090;" %>
                      </div>

                    </div>

                    <% @groups.each do |group| %>

                      <div class="row">

                        <div class="col-lg-2 col-sm-2 col-xs-2 my-questions">

                          <%= link_to public_group_path(group.id) do %>
                            <%= image_tag group.get_image, style: "border-radius: 50%;", class: "user_image_question" %>
                          <% end %>

                        </div>

                        <div class="col-lg-10 col-sm-10 col-xs-10 my-questions">

                          <p>
                            <span class="question-user-name" ><strong><%= group.name %></strong></span>
                            <span class="up-time text-muted"><%= group.users.count %> 人参加中</span>
                          </p>

                          <div class="question-body">

                            <div class="d-flex justify-content-between align-items-center">

                              <p class="question-contents"><%= group.introduction %></p>

                            </div>

                            <div class="text-right">

                              <span>

                                <%= link_to admin_group_path(group.id), class: "show-link" do %>
                                  <i class="fa-solid fa-door-open" style="color: #ec6090; font-size: 30px;"></i>
                                <% end %>

                              </span>

                            </div>

                          </div>

                        </div>

                      </div>

                      <div class="border-bottom border-dark"></div>

                    <% end %>

                  </div>

                </div>

              </div>

            </div>

            <div class="row">
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
                <div class="col-lg-6 col-sm-6 col-xs-6 pagi-nation">
                  <%= paginate @groups %>
                </div>
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>

app/views/admin/groups/show.html.erb
<%= stylesheet_link_tag 'show_questions', :media => "all" %>
<%= stylesheet_link_tag 'titles', :media => "all" %>
<%= stylesheet_link_tag 'questions', :media => "all" %>

<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <div class="row">

          <div class="col-lg-12">

            <div class="main-profile">

              <div class="row">

                <div class="col-lg-12">

                  <div class="album py-2">

                    <h1 class="my-questions-title"><strong><i class="fa-solid fa-clipboard-question"></i> <span>G</span>roup <span>D</span>etail</strong></h1>

                    <div class="row">

                      <div class="col-lg-2 col-sm-2 col-xs-2 my-questions">

                        <%= link_to public_group_path(@group.id) do %>
                          <%= image_tag @group.get_image, style: "border-radius: 50%;", class: "user_image_question" %>
                        <% end %>

                      </div>

                      <div class="col-lg-10 col-sm-10 col-xs-10 my-questions">

                        <p>
                          <span class="question-user-name" ><strong><%= @group.name %></strong></span>
                          <span class="up-time text-muted"><%= @group.users.count %> 人参加中</span>
                        </p>

                        <div class="question-body">

                          <div class="d-flex justify-content-between align-items-center">

                            <p class="question-contents"><%= @group.introduction %></p>

                          </div>

                        </div>

                      </div>

                    </div>

                    <div class="mb-5 border-bottom border-dark"></div>

                    <br>

                    <h1 class="comments"><strong><i class="fa-solid fa-comments"></i> <span>C</span>omments</strong></h1>

                    <% @group.group_comments.each do |group_comment| %>

                      <div class="row">

                        <div class="col-lg-1 col-sm-1 col-xs-1 my-questions">

                          <%= image_tag group_comment.user.get_profile_image, style: "border-radius: 100px;", class: "user_image_question" %>

                        </div>

                        <div class="col-lg-11 col-sm-11 col-xs-11 my-questions">

                          <p>
                            <span class="question-user-name" ><strong><%= group_comment.user.user_name %></strong></span>
                            <span class="up-time text-muted"><%= group_comment.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></span>
                          </p>

                          <div class="question-body">

                            <div class="d-flex justify-content-between align-items-center">

                              <p class="question-contents"><%= group_comment.group_comment %></p>

                            </div>

                            <div class="text-right">

                              <% if user_signed_in? && group_comment.user == current_user %>
                                <%= link_to public_group_group_comment_path(group_comment.group), method: :delete do %>
                                  <i class="fa-solid fa-trash-can" style="color: red; font-size: 30px;"></i>
                                <% end %>
                              <% elsif admin_signed_in? %>
                                <%= link_to "管理者削除", admin_group_group_comment_path(group_comment.group.id, group_comment.id), method: :delete, class: "btn btn-sm btn-danger p-0 p-1", style: "font-size: 20px;" %>
                              <% end %>

                            </div>

                          </div>

                        </div>

                      </div>

                      <div class="border-bottom border-dark"></div>

                    <% end %>

                  </div>

                </div>

              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>






              <%# @group.users.each do |member| %>
                <%#= member.name %>
              <%# end %>