config/routes.rb
Rails.application.routes.draw do

  get 'homes/top'
  get 'homes/about'
  get "search_result" => "searchs#search_result"
  root to: "homes#top"

  # 管理者
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :admin do
    resources :games
  end

  namespace :admin do
    resources :questions
    resources :questions do
      resources :comments, only: [:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :admin do
    resources :tags
  end

  namespace :admin do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :admin do
    devise_scope :user do
      post 'users/:id', to: 'sessions#guest_sign_in', as: 'guest_sign_in'
    end

    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups
    end

  #ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :games
  end

  namespace :public do
    resources :questions
    resources :questions, except: [:destroy] do
      resources :comments, only: [:create,:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :public do
    resources :tags
  end

  namespace :public do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :public do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :public do
    devise_scope :user do
      post 'user/guest_sign_in' => 'sessions#guest_sign_in', as: 'guest_sign_in'
    end
  end

  namespace :public do
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups do
      get "join" => "groups#join"
      get "group/:id/member" => "groups#member", as: 'members'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy

  validates :user_name, presence: true, uniqueness: true,
                   length: { minimum: 1, maximum: 20 }

  validates :introduction, length: { maximum: 350 }

  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  # 検索方法分岐
  def self.looks(search, word)
    # if search == "perfect_match"
    #   @user = User.where("last_name LIKE?", "#{word}")
    # elsif search == "forward_match"
    #   @user = User.where("last_name LIKE?","#{word}%")
    # elsif search == "backward_match"
    #   @user = User.where("last_name LIKE?","%#{word}")
    # elsif search == "partial_match"
      @user = User.where("user_name LIKE?","%#{word}%")
    #   @user = User.all

  end

  def self.guest
    find_or_create_by!(email: 'guest@guest') do |user|
      user.user_name = 'guest'
      user.telephone_number = '000'
      user.password = SecureRandom.urlsafe_base64
      # user.skip_confirmation!
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.order("id DESC").page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @questions = @user.questions.order("id DESC").page(params[:page]).per(20)
    @tag_list = Tag.all
    @tag_list = Tag.order("id DESC")
    @question = Question.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User was successfully updated.'
      redirect_to public_user_path(@user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :profile_image,:password, :introduction, :email, :telephone_number, :favorite_game, :title, :question, :image)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<%= stylesheet_link_tag 'edit_users', :media => "all" %>

<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <h1 class="h2 mb-5 font-weight-normal" style="text-align: center; font-size: 40px;"><strong><span>C</span>hange <span>U</span>ser <span>I</span>nfo</strong></h1>

        <p class="errors">
          <% if @user.errors.any? %>
            <%#= @uesr.error.count %>
            <ul class="error-details">
              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </p>

        <%= form_with model: @user, url: public_user_path(@user.id), method: :patch do |f| %>

          <div class="row">

            <div class="col-lg-6 col-sm-6 col-xs-6">

              <div class="user-edit-form">

                <label for="user_name">ユーザーネーム</label>

                <%= f.text_field :user_name, class:'form-control user_name', placeholder: "（20文字以内）", autofocus: true, maxlength: "20" %>

              </div>

              <div class="user-edit-form">

                <label for="user_image">ユーザー画像</label>

                <%= f.file_field :profile_image, class: 'form-control-file image', accept: "image/*" %>

              </div>

              <div class="user-edit-form">

                <label for="user_email">メールアドレス</label>

                <%= f.text_field :email, class:'form-control user_email' %>

              </div>

              <div class="user-edit-form">

                <label for="user_telephone_number">電話番号</label>

                <%= f.text_field :telephone_number, class:'form-control user_telephone_number' %>

              </div>

            </div>

            <div class="col-lg-6 col-sm-6 col-xs-6">

              <!--<div class="user-edit-form">-->

              <!--  <label for="user_password">パスワード</label>-->

                <%#= f.password_field :password, class:'form-control user_password', placeholder: "新パスワード6文字以上", autocomplete: "new-password" %>
                <%#= f.password_field :password_confirmation, class:'form-control user_password', placeholder: "新パスワード確認", autocomplete: "new-password" %>
                <%#= f.password_field :current_password, class:'form-control user_password', placeholder: "現在のパスワード", autocomplete: "current_password" %>

              <!--</div>-->

              <div class="user-edit-form">

                <label for="user_favorite_game">お気に入りのゲーム</label></label>

                <%= f.text_field :favorite_game, placeholder: "１番好きなゲームタイトルを入力", class:'form-control user_favorite_game' %>

              </div>

              <div class="user-edit-form">

                <label for="user_introduction">自己紹介</label>

                  <%= f.text_area :introduction, class:'form-control user_introduction', placeholder: "自己紹介文を入力（350文字以内）", size: '40x5', autofocus: true, maxlength: "350" %>

              </div>

            </div>

          </div>

          <div class="row">

            <div class="col-lg-4 col-sm-4 col-xs-4"></div>

            <div class="edit-button col-lg-4 col-sm-4 col-xs-4">

              <%= f.submit 'Edit User', class:'btn btn-outline-light', style: "color: #ec6090;" %>

            </div>

            <div class="delete-button col-lg-4 col-sm-4 col-xs-4">
              <%= link_to '退会させる', admin_unsubscribe_path, class: "glyphicon glyphicon-tint btn btn-outline-danger"%>
            </div>

          </div>

        <% end %>

      </div>

    </div>

  </div>

</div>

app/views/admin/users/index.html.erb
<%= stylesheet_link_tag 'questions', :media => "all" %>
<%= stylesheet_link_tag 'titles', :media => "all" %>
<%= stylesheet_link_tag 'tags', :media => "all" %>



<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <div class="row">

          <div class="col-lg-12">

            <div class="main-profile">

              <div class="row">

                <div class="col-lg-12">

                  <div class="album py-2">

                    <h1 class="my-questions-title"><strong><i class="fa-solid fa-clipboard-question"></i><span>U</span>sers</strong></h1>

                    <% @users.each do |user| %>

                      <div class="row">

                        <div class="col-lg-2 col-sm-2 col-xs-2 my-questions">

                          <%= link_to public_user_path(user.id) do %>
                            <%= image_tag user.get_profile_image, style: "border-radius: 50%;", class: "user_image_question" %>
                          <% end %>

                        </div>

                        <div class="col-lg-10 col-sm-10 col-xs-10 my-questions">

                          <p>
                            <span class="question-user-name" ><strong><%= user.user_name %></strong></span>
                            <span class="up-time text-muted"><%= user.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></span>
                          </p>

                          <div class="question-body">

                            <p class="question-contents"><span class="search-users" style="color: white;">Favorite Game</span>: <%= user.favorite_game %></p>

                            <div class="d-flex justify-content-between align-items-center">

                              <p class="question-contents"><span class="search-users" style="color: white;">Introduction</span>:<br><%= user.introduction %></p>

                            </div>

                          </div>

                          <div class="delete-button col-lg-4 col-sm-4 col-xs-4">
                            <span class="up-button-delete"><%= link_to "退会させる", admin_withdraw_path(user.id), method: :patch, data: {confirm: "本当に退会させてもよろしいですか？"}, class: "glyphicon glyphicon-home btn btn-outline-danger" %></span>
                          </div>

                        </div>

                      </div>

                      <div class="border-bottom border-dark"></div>

                    <% end %>

                  </div>

                </div>

              </div>

            </div>

            <div class="row">
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
                <div class="col-lg-6 col-sm-6 col-xs-6 pagi-nation">
                  <%= paginate @users %>
                </div>
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>

app/views/admin/users/show.html.erb
<%= stylesheet_link_tag 'users', :media => "all" %>
<%= stylesheet_link_tag 'tags', :media => "all" %>
<%= stylesheet_link_tag 'titles', :media => "all" %>

<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <div class="row">

          <div class="col-lg-12">

            <div class="main-profile">

              <h1 class="user-info"><strong><i class="fa-solid fa-user-astronaut"></i> <span>U</span>ser <span>I</span>nfo</strong></h1>

              <div class="row">

                <div class="col-lg-4 col-sm-12 col-xs-12">

                  <%= image_tag @user.get_profile_image, style: "border-radius: 23px;", class: "user-image" %>

                </div>

                <div class="col-lg-4 col-sm-12 col-xs-12 align-self-center">

                  <ul>
                    <li>Name <span><%= @user.user_name %></span></li>
                    <li>Favorite Game <span><%= @user.favorite_game %></span></li>
                    <li>Introduction <p class="users-introduction"><%= @user.introduction %></p></li>
                    <p class="main-border-button">
                      <% if @user = current_user %>
                        <%= link_to edit_public_user_path, class: "btn btn-outline-light", style: "color: #ec6090;" do %>
                         Edit User
                        <% end %>
                      <% else %>
                      <% end %>
                    </p>
                  </ul>

                </div>

                <div class="col-lg-4 col-sm-12 col-xs-12">

                  <div class="main-info header-text">

                    <h2 class="text-center">Ouick Question!!</h4>

                    <%= form_with model: @question, url: public_questions_path, method: :post do |f| %>

                      <div class="title-form">

                        <%= f.text_field :title, placeholder: "質問タイトル(100文字以内)", class:'form-control', autofocus: true, maxlength: "100" %>

                      </div>

                      <div class="image-form">

                        <%= f.file_field :question_images, multiple: true, accept: "image/*", placeholder: "関連画像", class:'form-control' %>

                      </div>

                      <div class="tag-form">

                          <%= f.text_field :tag_name, placeholder: "タグ  ”,”で区切ると複数投稿できます", class:'form-control' %>

                      </div>

                      <div class="question-form">

                        <%= f.text_area :question, placeholder: "質問内容", class:'form-control', size: '40x5', autofocus: true, maxlength: "500" %>

                      </div>

                      <div class="up-button">

                        <%= f.submit 'Up Question!!', class:'btn btn-outline-light', style: "color: #ec6090;" %>

                      </div>

                    <% end %>

                  </div>

                </div>

              </div>

            </div>

          </div>

        </div>

        <div class="row mt-4">

          <div class="col-lg-12">

            <div class="main-profile">

              <div class="row">

                <div class="col-lg-12">

                  <div class="album py-2">

                    <h1 class="tag-title"><strong><i class="fa-solid fa-tags"></i> <span>T</span>ags</strong></h1>

                    <div class="tag-list">

                      <% @tag_list.each do |list| %>
                        <%= link_to public_search_tag_path(tag_id: list.id), class:"btn btn-outline-light" do %>
                          <span>
                            <i class="fas fa-tag"></i> <%= list.tag_name %><%= "(#{list.questions.count})" %>
                          </span>
                        <% end %>
                      <% end %>

                    </div>

                    <div class="pt-4 mb-5 content-border"></div>

                    <div><br></div>

                    <% if @user.id == current_user.id %>
                        <h1 class="my-questions-title"><strong><i class="fa-solid fa-clipboard-question"></i> <span>M</span>y <span>Q</span>uestions</strong></h1>
                      <% else %>
                        <h1 class="my-questions-title"><strong><i class="fa-solid fa-clipboard-question"></i> <span><%= @user.user_name %></span>'s <span>Q</span>uestions</strong></h1>
                    <% end %>

                    <% @questions.each do |question| %>

                      <div class="row">

                        <div class="col-lg-2 col-sm-2 col-xs-2 my-questions">

                          <%= image_tag @user.get_profile_image, style: "border-radius: 50%;", class: "user_image_question" %>

                        </div>

                        <div class="col-lg-10 col-sm-10 col-xs-10 my-questions">

                          <p>
                            <span class="question-user-name" ><strong><%= @user.user_name %></strong></span>
                            <span class="up-time text-muted"><%= question.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></span>
                          </p>

                          <div class="question-body">

                            <p class="question-title"><strong><%= question.title %></strong></p>

                            <div class="d-flex justify-content-between align-items-center">

                              <p class="question-contents"><%= question.question %></p>

                            </div>

                            <div class="col-lg-12 col-sm-12 col-xs-12 question-images">
                              <% if question.question_images.attached? %>
                                <% question.question_images.each do |image| %>
                                  <%= image_tag image, style: "border-radius: 20px;", class:'question-image' %>
                                <% end %>
                              <% end %>
                            </div>

                            <br>
                            <div class="text-right">

                              <span>
                                <%= link_to public_question_path(question.id), class: "show-link" do  %>
                                  <i class="fa-solid fa-door-open" style="color: #ec6090; font-size: 30px;"></i>
                                <% end %>
                              </span>

                              <span>

                                <% if question.bookmarked_by?(current_user) %>

                                  <td>
                                    <%= link_to public_question_bookmarks_path(question.id), method: :delete do %>
                                      <i class="fa-solid fa-bookmark" style="color: #ec6090; font-size: 30px;"></i>
                                    <% end %>
                                  </td>

                                <% else %>

                                  <td>
                                    <%= link_to public_question_bookmarks_path(question.id), method: :post do %>
                                      <i class="fa-regular fa-bookmark" style="color: #ec6090; font-size: 30px;"></i>
                                    <% end %>
                                  </td>

                                <% end %>

                              </span>

                            </div>

                          </div>

                        </div>

                      </div>

                      <div class="border-bottom border-dark"></div>

                    <% end %>

                  </div>

                </div>

              </div>

            </div>

            <div class="row">
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
                <div class="col-lg-6 col-sm-6 col-xs-6 pagi-nation">
                  <%= paginate @questions %>
                </div>
              <div class="col-lg-3 col-sm-3 col-xs-3"></div>
            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>

app/views/admin/users/unsubscribe.html.erb
<%= stylesheet_link_tag 'withdraw', :media => "all" %>

<div class="container">

  <div class="row">

    <div class="col-lg-12">

      <div class="page-content">

        <div class="row">

          <div class="col-lg-12">

            <div class="main-profile">

              <h1 class="h2 mb-5 font-weight-normal" style="text-align: center; font-size: 40px;"><strong><span>W</span>ithdraw <span>U</span>ser</strong></h1>

              <div class="row">

                <div class="col-12 quite">

                  <h2></h2><strong>本当に退会させますか？</strong></h2>

                    <span class="up-button"><%= link_to "退会させない", admin_users_path(@user.id), class: 'glyphicon glyphicon-home btn btn-outline-light' %></span>
                    <span class="up-button-delete"><%= link_to "退会させる", admin_withdraw_path(@user.id), method: :patch, data: {confirm: "本当に退会させてもよろしいですか？"}, class: "glyphicon glyphicon-home btn btn-outline-danger" %></span>

                </div>

              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>