config/routes.rb
Rails.application.routes.draw do

  get 'homes/top'
  get 'homes/about'
  get "search_result" => "searchs#search_result"
  root to: "homes#top"

  # 管理者
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :admin do
    resources :games
  end

  namespace :admin do
    resources :questions
    resources :questions do
      resources :comments, only: [:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :admin do
    resources :tags
  end

  namespace :admin do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :admin do
    devise_scope :user do
      post 'users/:id', to: 'sessions#guest_sign_in', as: 'guest_sign_in'
    end

    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups
    end

  #ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    resources :questions, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :games
  end

  namespace :public do
    resources :questions
    resources :questions, except: [:destroy] do
      resources :comments, only: [:create,:destroy]
    end
    get 'bookmarks' => 'questions#bookmark'
  end

  namespace :public do
    resources :tags
  end

  namespace :public do
    resources :groups, except: [:destroy] do
      resources :group_comments, only: [:create,:destroy]
    end
  end

  namespace :public do
    get "search" => "searches#search"
    get "search_tag" => "questions#search_tag"
  end

  namespace :public do
    devise_scope :user do
      post 'user/guest_sign_in' => 'sessions#guest_sign_in', as: 'guest_sign_in'
    end
  end

  namespace :public do
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw/:id' => 'users#withdraw', as: 'withdraw'

    resources :users
    resources :groups do
      get "join" => "groups#join"
      get "group/:id/member" => "groups#member", as: 'members'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :question

  # validates :user_id, uniqueness: { scope: :question_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, presence: true, length: { maximum: 1000 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/group_comment.rb
class GroupComment < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/question.rb
class Question < ApplicationRecord
  has_one_attached :image
  has_many_attached:question_images

  belongs_to :user
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 200 }
  validates :question, presence: true, length: { maximum: 1000 }

  # ブックマーク機能
  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  # 検索機能
  def self.looks(search, word)
      @question = Question.where("title LIKE?","%#{word}%")
  end

  # タグ検索機能
  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(tag_name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_tagmap = Tag.find_or_create_by(tag_name: new)
      self.tags << new_tagmap
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tagmaps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :questions, through: :tagmaps , dependent: :destroy

  def self.looks(search, word)

    @tag = Tag.where("tag_name LIKE?","%#{word}%")

  end

end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy

  validates :user_name, presence: true, uniqueness: true,
                   length: { minimum: 1, maximum: 20 }

  validates :introduction, length: { maximum: 350 }

  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  # 検索方法分岐
  def self.looks(search, word)
    # if search == "perfect_match"
    #   @user = User.where("last_name LIKE?", "#{word}")
    # elsif search == "forward_match"
    #   @user = User.where("last_name LIKE?","#{word}%")
    # elsif search == "backward_match"
    #   @user = User.where("last_name LIKE?","%#{word}")
    # elsif search == "partial_match"
      @user = User.where("user_name LIKE?","%#{word}%")
    #   @user = User.all

  end

  def self.guest
    find_or_create_by!(email: 'guest@guest') do |user|
      user.user_name = 'guest'
      user.telephone_number = '000'
      user.password = SecureRandom.urlsafe_base64
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @questions = Question.looks(params[:search], params[:word])
    end
  end

  def search_result
    @questions = Question.all
  end

end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %>
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %>
<%# end %>

<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
<%# end %>

<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<%# end %>

<%#- if devise_mapping.omniauthable? %>
  <%#- resource_class.omniauth_providers.each do |provider| %>
    <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <%# end %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameQuestion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/9ed88e2d37.js" crossorigin="anonymous"></script>

  </head>

  <body style="padding-top:8rem" class="bg-black text-light">

    <header>

      <nav class="navbar navbar-expand-xl navbar-dark text-dark fixed-top p-1">

        <div class="container">

          <% if user_signed_in? %>
            <%= link_to public_questions_path, class:"navbar-brand text-light" do %>
              <%= image_tag 'Game.png', size: "90x90" %>
            <% end %>
          <% else %>
            <%= link_to root_path, class:"navbar-brand text-light" do %>
              <%= image_tag 'Game.png', size: "90x90" %>
            <% end %>
          <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon navbar"></span>

          </button>

          <div class="navbar-collapse collapse" id="navbarNavDropdown">

            <% if user_signed_in? %>
              <div class="search_form">
                <%= form_with url: public_search_path, local: true, method: :get do |f| %>
                  <%= f.select :range, options_for_select([['Question'], ['User'], ['Tag']]), style: "color: #666;" %>
                  <%= f.text_field :word, placeholder: "Search..." %>
                  <%#= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]), style: "color: #666;" %>
                  <%= f.button :type => "submit", class: "btn btn-outline-light" ,style: "border-radius: 20%; color: #ec6090; border: 1px solid #ec6090;" do %>
                    <i class="fa-solid fa-magnifying-glass"></i>
                  <% end %>
                <% end %>
              </div>
            <% end %>

            <ul class="navbar-nav nav-tabs ml-auto mb-2 mb-xl-0">

              <% if user_signed_in? %>

                <li class="nav-item">
                  <%= link_to public_user_path(current_user.id), class:'nav-link link-danger text-light' do  %>
                    <i class="fa-solid fa-user-astronaut" style="color: #ec6090; font-size: 20px;"></i> Mypage
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to public_questions_path, class:'nav-link text-light' do  %>
                    <i class="fa-solid fa-clipboard-question" style="color: #ec6090; font-size: 20px;"></i> Questions
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to public_bookmarks_path, class:'nav-link text-light' do  %>
                    <i class="fa-solid fa-book-bookmark" style="color: #ec6090; font-size: 20px;"></i> Bookmarks
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to public_groups_path, class:'nav-link text-light' do  %>
                    <i class="fa-solid fa-people-group" style="color: #ec6090; font-size: 20px;"></i> Groups
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to destroy_user_session_path, class:'nav-link text-light', method: :delete do  %>
                    <i class="fa-solid fa-right-from-bracket" style="color: #ec6090; font-size: 20px;"></i> Logout
                  <% end %>
                </li>

              <% elsif admin_signed_in? %>

                <li class="nav-item">
                  <%= link_to admin_users_path, class:'nav-link link-danger text-light' do  %>
                    <i class="fa-solid fa-user-astronaut" style="color: #ec6090; font-size: 20px;"></i> Users
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to admin_questions_path, class:'nav-link text-light' do  %>
                    <i class="fa-solid fa-clipboard-question" style="color: #ec6090; font-size: 20px;"></i> Questions
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to admin_groups_path, class:'nav-link text-light' do  %>
                    <i class="fa-solid fa-people-group" style="color: #ec6090; font-size: 20px;"></i> Groups
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, class:'nav-link text-light', method: :delete do  %>
                    <i class="fa-solid fa-right-from-bracket" style="color: #ec6090; font-size: 20px;"></i> Logout
                  <% end %>
                </li>

              <% else %>

              <% end %>

            </ul>

          </div>

        </div>

      </nav>

    </header>

    <% if user_signed_in? %>
      <div class="question-button">
        <%= link_to new_public_question_path, class: "btn btn-outline-light", style: "border-radius: 90px; color: #FF3366;" do %>
          <i class="fa-solid fa-question"></i><br>質問
        <% end %>
      </div>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/share/_comment_form.html.erb
<%= form_with model: [question,comment], url: public_question_comments_path(question), method: :post do |f| %>

  <div class="row">

    <div class="col-lg-12 col-sm-12 col-xs-12 comment-form">

      <%= f.text_area :comment, placeholder: "コメントをここに(500文字以内)", class:"form-control", size: "40x5" %>

    </div>

    <div class="col-lg-12 col-sm-12 col-xs-12 comment-button">

      <%= f.submit 'Comment!!', class:'btn btn-outline-light' %>

    </div>

  </div>

<% end %>

app/views/share/_group_comment_form.html.erb
<%= form_with model: [group,group_comment], url: public_group_group_comments_path(group.id), method: :post do |f| %>

  <div class="row">

    <div class="col-lg-12 col-sm-12 col-xs-12 comment-form">

      <%= f.text_area :group_comment, placeholder: "コメントをここに(500文字以内)", class:"form-control", size: "40x5" %>

    </div>

    <div class="col-lg-12 col-sm-12 col-xs-12 comment-button">

      <%= f.submit 'Comment!!', class:'btn btn-outline-light' %>

    </div>

  </div>

<% end %>

app/views/share/_paginate.html.erb
<div class="row">
  <div class="col-lg-3 col-sm-3 col-xs-3"></div>
    <div class="col-lg-6 col-sm-6 col-xs-6 pagi-nation">
      <%= paginate questions %>
    </div>
  <div class="col-lg-3 col-sm-3 col-xs-3"></div>
</div>

app/views/share/_questions.html.erb
<% questions.each do |question| %>

  <div class="row">

    <div class="col-lg-2 col-sm-2 my-questions">

      <%= link_to public_user_path(question.user.id) do %>
        <%= image_tag question.user.get_profile_image, style: "border-radius: 50%;", class: "user_image_question" %>
      <% end %>

    </div>

    <div class="col-lg-10 col-sm-10 my-questions">

      <p class="question_user_name"><span class="question-user-name" ><strong><%= question.user.user_name %></strong></span></p>

      <p class="text-right up-time"><span class="text-muted"><%= question.created_at.strftime("%Y/%m/%d/%H:%M") %></span></p>

      <div class="question-body">

        <p class="question-title"><strong><%= question.title %></strong></p>

        <div class="d-flex justify-content-between align-items-center">

          <p class="question-contents"><%= question.question %></p>

        </div>

        <div class="question-images">
          <% if question.question_images.attached? %>
            <% question.question_images.each do |image| %>
              <%= image_tag image, style: "border-radius: 20px;", class:'question-image' %>
            <% end %>
          <% end %>
        </div>

        <div class="text-right">

          <span>
            <%= link_to public_question_path(question.id), class: "show-link" do  %>
              <i class="fa-solid fa-door-open" style="color: #ec6090; font-size: 30px;"></i>
            <% end %>
          </span>

          <span id="bookmark_button_<%= question.id %>">

            <%= render "public/bookmarks/bookmark", question: question %>

          </span>

        </div>

      </div>

    </div>

  </div>

  <div class="border-bottom border-dark"></div>

<% end %>

app/views/share/_tags.html.erb
<% tag_list.each do |list| %>
  <%= link_to public_search_tag_path(tag_id: list.id), class:"btn btn-outline-light" do %>
    <span style="padding: ">
      <i class="fas fa-tag"></i> <%= list.tag_name %><%= "(#{list.questions.count})" %>
    </span>
  <% end %>
<% end %>

app/views/share/_unbookmark.html..erb
<td>
  <%= link_to public_question_bookmarks_path(question.id), method: :post, remote: true do %>
    <i class="fa-regular fa-bookmark" style="color: #ec6090; font-size: 30px;"></i>
  <% end %>
</td>

app/views/share/_user_questions.html.erb
<% questions.each do |question| %>

  <div class="row">

    <div class="col-lg-2 col-sm-2 col-xs-2 my-questions">

      <%= image_tag user.get_profile_image, style: "border-radius: 50%;", class: "user_image_question" %>

    </div>

    <div class="col-lg-10 col-sm-10 col-xs-10 my-questions">

      <p class="question_user_name"><span class="question-user-name" ><strong><%= user.user_name %></strong></span></p>

      <p class="text-right up-time"><span class="text-muted"><%= question.created_at.strftime("%Y/%m/%d/%H:%M") %></span></p>

      <div class="question-body">

        <p class="question-title"><strong><%= question.title %></strong></p>

        <div class="d-flex justify-content-between align-items-center">

          <p class="question-contents"><%= question.question %></p>

        </div>

        <div class="col-lg-12 col-sm-12 col-xs-12 question-images">
          <% if question.question_images.attached? %>
            <% question.question_images.each do |image| %>
              <%= image_tag image, style: "border-radius: 20px;", class:'question-image' %>
            <% end %>
          <% end %>
        </div>

        <br>
        <div class="text-right">

          <span>
            <%= link_to public_question_path(question.id), class: "show-link" do  %>
              <i class="fa-solid fa-door-open" style="color: #ec6090; font-size: 30px;"></i>
            <% end %>
          </span>

          <span id="bookmark_button_<%= question.id %>">

            <%= render "public/bookmarks/bookmark", question: question %>

          </span>

        </div>

      </div>

    </div>

  </div>

  <div class="border-bottom border-dark"></div>

<% end %>